'use strict';
const $=id=>document.getElementById(id),match=new Match(),canvas=$('court'),ctx=canvas.getContext('2d');
const keys=new Set();let audio,master,buffers={},last=performance.now(),bellAt=0,warning=false;
const samples={throw:'throw.ogg',save:'save.ogg',dive:'dive.ogg',goal:'goal.ogg',bell:'bell.ogg'};
async function initAudio(){if(!audio){audio=new AudioContext();master=audio.createGain();master.gain.value=Number($('volume').value)/100;master.connect(audio.destination);await Promise.all(Object.entries(samples).map(async([name,file])=>{try{const r=await fetch('assets/'+file);buffers[name]=await audio.decodeAudioData(await r.arrayBuffer());}catch(e){console.warn('Audio no disponible',file,e);}}));}await audio.resume();}
function sound(name,pan=0,gain=1,rate=1){if(!audio||!buffers[name])return;const source=audio.createBufferSource(),p=audio.createStereoPanner(),g=audio.createGain();source.buffer=buffers[name];source.playbackRate.value=rate;p.pan.value=Math.max(-1,Math.min(1,pan));g.gain.value=gain;source.connect(g);g.connect(p);p.connect(master);source.start();}
function whistle(){if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=2400;g.gain.setValueAtTime(0.1,audio.currentTime);g.gain.exponentialRampToValueAtTime(0.001,audio.currentTime+.25);o.connect(g);g.connect(master);o.start();o.stop(audio.currentTime+.26);}
function speak(text,interrupt=false){if(!$('voice').checked||!('speechSynthesis'in window))return;if(interrupt)speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='es-ES';u.rate=1.12;const v=speechSynthesis.getVoices().find(v=>v.lang.startsWith('es'));if(v)u.voice=v;speechSynthesis.speak(u);}
function announce(){const ev=match.events.splice(0);for(const e of ev){$('status').textContent=e.text;if(e.type==='whistle')whistle();else sound(e.type,0,e.type==='goal'?0.6:0.8);speak(e.text,true);}}
function begin(){initAudio();if(match.phase==='break')match.resume();else match.start();announce();}
function act(){initAudio();if(match.phase!=='play')return;if(match.owner===0&&!match.ball)match.throwBall(0,Number($('aim').value),Number($('power').value)/100,$('style').value);else match.dive();announce();}
function report(){const side=match.ball?(match.ball.x<3?'izquierda':match.ball.x>6?'derecha':'centro'):'sin balón en movimiento';speak(`Tu equipo ${match.score[0]}, rival ${match.score[1]}. ${Math.ceil(match.clock)} segundos. ${side}. Defensor ${match.selected+1}. Apuntando a ${Number($('aim').value).toFixed(1)} metros. Potencia ${$('power').value} por ciento. Posesión ${match.owner===0?'tuya':'rival'}.`,true);}
function draw(){const w=canvas.width,h=canvas.height;ctx.fillStyle='#0e1e2c';ctx.fillRect(0,0,w,h);if($('blind').checked){ctx.fillStyle='#71e5c2';ctx.font='24px Segoe UI';ctx.textAlign='center';ctx.fillText('ANTIFAZ ACTIVADO',w/2,h/2);ctx.font='14px Segoe UI';ctx.fillText('Escucha · Localiza · Bloquea',w/2,h/2+32);return;}
 const px=y=>50+y/18*720,py=x=>40+x/9*360;ctx.fillStyle='#183f4b';ctx.fillRect(50,40,720,360);ctx.fillStyle='#214c56';ctx.fillRect(50,40,120,360);ctx.fillRect(650,40,120,360);ctx.strokeStyle='#8acbbb';ctx.lineWidth=2;ctx.strokeRect(50,40,720,360);for(const y of [3,6,9,12,15]){ctx.beginPath();ctx.moveTo(px(y),40);ctx.lineTo(px(y),400);ctx.stroke();}ctx.strokeStyle='#527f88';for(const x of [3,6]){ctx.beginPath();ctx.moveTo(50,py(x));ctx.lineTo(170,py(x));ctx.moveTo(650,py(x));ctx.lineTo(770,py(x));ctx.stroke();}ctx.fillStyle='#71e5c2';ctx.fillRect(40,40,7,360);ctx.fillStyle='#ffb388';ctx.fillRect(773,40,7,360);
 for(let t=0;t<2;t++)for(let i=0;i<3;i++){if(match.penalty&&t===match.penalty.offender&&i!==(t===0?match.selected:1))continue;const x=px(t===0?1.6:16.4),y=py(match.players[t][i]);ctx.fillStyle=t===0?'#71e5c2':'#ffb388';ctx.beginPath();ctx.ellipse(x,y,t===0&&match.dives[i]>0?12:15,t===0&&match.dives[i]>0?54:15,0,0,Math.PI*2);ctx.fill();if(t===0&&i===match.selected){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,22,0,Math.PI*2);ctx.stroke();}ctx.fillStyle='#0a2028';ctx.font='bold 13px Segoe UI';ctx.textAlign='center';ctx.fillText(String(i+1),x,y+5);}
 if(match.owner===0&&!match.ball){ctx.strokeStyle='#71e5c280';ctx.setLineDash([6,6]);ctx.beginPath();ctx.moveTo(px(2),py(match.players[0][match.selected]));ctx.lineTo(px(16),py(Number($('aim').value)));ctx.stroke();ctx.setLineDash([]);}if(match.ball){ctx.fillStyle='#ffe9a6';ctx.shadowColor='#ffdf72';ctx.shadowBlur=14;ctx.beginPath();ctx.arc(px(match.ball.y),py(match.ball.x),9,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}ctx.fillStyle='#a4c6cf';ctx.font='12px Segoe UI';ctx.textAlign='center';ctx.fillText('TU PORTERÍA',105,425);ctx.fillText('ZONA NEUTRAL',410,425);ctx.fillText('PORTERÍA RIVAL',715,425);}
function frame(now){const dt=Math.min(.1,(now-last)/1000);last=now;if(keys.has('ArrowLeft'))match.move(-1,dt);if(keys.has('ArrowRight'))match.move(1,dt);if(keys.has('a'))$('aim').value=Math.max(0,Number($('aim').value)-dt*4);if(keys.has('d'))$('aim').value=Math.min(9,Number($('aim').value)+dt*4);match.step(dt);if(match.phase==='play'&&match.ball&&now-bellAt>160){const b=match.ball;const distance=Math.abs(b.y-2);sound('bell',(b.x-4.5)/4.5,.08+.4*(1-distance/18),.9+distance/90);bellAt=now;}if(match.phase==='play'&&match.owner===0&&!match.ball&&match.hold>=7&&!warning){speak('Quedan tres segundos.',true);warning=true;}if(match.hold<1)warning=false;announce();$('home').textContent=match.score[0];$('away').textContent=match.score[1];$('clock').textContent=String(Math.floor(match.clock/60)).padStart(2,'0')+':'+String(Math.floor(match.clock%60)).padStart(2,'0');$('period').textContent=['','1.ª mitad','2.ª mitad','Prórroga 1','Prórroga 2','Lanzamientos extra'][match.period];$('possession').textContent=match.phase==='finished'?'Partido terminado':match.penalty?'Penalti':match.phase==='timeout'?`Tiempo muerto: ${Math.ceil(match.wait)} s`:match.ball?'Balón en movimiento':`Posesión: ${match.owner===0?'tu equipo':'rival'} · ${Math.max(0,10-match.hold).toFixed(1)} s`;draw();requestAnimationFrame(frame);}
$('start').onclick=begin;$('pause').onclick=()=>{match.pause();announce();};$('timeout').onclick=()=>{match.timeout();announce();};$('sub').onclick=()=>{match.substitute();announce();};$('ref').onclick=()=>{match.referee($('foul').value);announce();};$('new').onclick=()=>{match.reset();announce();};$('practice').onclick=()=>{match.reset(true);begin();};$('volume').oninput=()=>{if(master)master.gain.value=Number($('volume').value)/100;};
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','BUTTON','SUMMARY'].includes(e.target.tagName))return;const k=e.key.length===1?e.key.toLowerCase():e.key;if([' ','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','F1'].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;if(k==='Enter')begin();else if(k===' ')act();else if(['1','2','3'].includes(k)){match.selected=Number(k)-1;speak(`Defensor ${k}`,true);}else if(k==='p')$('pause').click();else if(k==='t')$('timeout').click();else if(k==='s')$('sub').click();else if(k==='m'){$('blind').checked=!$('blind').checked;speak($('blind').checked?'Antifaz activado.':'Antifaz desactivado.',true);}else if(k==='v'){$('voice').checked=!$('voice').checked;if(!$('voice').checked)speechSynthesis.cancel();}else if(k==='h')report();else if(k==='ArrowUp')$('power').value=Math.min(100,Number($('power').value)+10);else if(k==='ArrowDown')$('power').value=Math.max(10,Number($('power').value)-10);else if(k==='F1')speak('Goalball. Enter empieza. Uno, dos y tres seleccionan defensor. Flechas izquierda y derecha mueven al defensor. Espacio bloquea o lanza. A y D apuntan. Flechas arriba y abajo ajustan potencia. H anuncia marcador. M activa antifaz. P pausa. T solicita tiempo muerto. S realiza sustitución.',true);});
window.addEventListener('keyup',e=>{const k=e.key.toLowerCase();keys.delete(e.key.length===1?k:e.key);if(['a','d','arrowup','arrowdown'].includes(k)&&!['INPUT','SELECT'].includes(e.target.tagName))speak(`Destino ${Number($('aim').value).toFixed(1)} metros. Potencia ${$('power').value} por ciento.`,true);});document.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>b.blur()));window.addEventListener('blur',()=>{keys.clear();if(match.phase==='play'){match.pause();announce();}});window.goalball={match,begin,act};requestAnimationFrame(frame);
